apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway-server
  labels:
    app: gateway-server
spec:
  selector:
    matchLabels:
      app: gateway-server
  template:
    metadata:
      labels:
        app: gateway-server
    spec:
      containers:
        - name: gateway-server
          image: nttdatabootcampacr.azurecr.io/gateway-server:1.0
          imagePullPolicy: Always
          ports:
            - containerPort: 7001
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: docker
      imagePullSecrets:
        - name: bootcampsecret