version: "3.7"
services:
  gateway-server:
    container_name: gateway-server
    build: .
    restart: always
    environment:
      - "SPRING_PROFILES_ACTIVE=docker"
    ports:
      - "7001:7001"
networks:
  default:
    name: custom-network