eureka:
  client:
    serviceUrl:
      defaultZone: https://bootcamp-eurekaserver.azurewebsites.net:443/eureka
  instance:
    hostname: bootcamp-gatewayserver.azurewebsites.net
    secure-port-enabled: true
    nonsecure-port-enabled: false
    nonSecurePort: 80
    securePort: 443
    instanceId: ${eureka.instance.hostname}:${spring.application.name}:443
    statusPageUrl: https://${eureka.hostname}:443/actuator/info
    healthCheckUrl: https://${eureka.hostname}:443/actuator/health
    secureHealthCheckUrl: https://${eureka.hostname}:443/actuator/health