server:
  port: 7001

spring:
  profiles:
    active: local
  application:
    name: gateway

  cloud:
    gateway:
      routes:
        - id: account-service
          uri: lb://account-service
          predicates:
            - Path=/accounts/**
        - id: transaction-service
          uri: lb://transaction-service
          predicates:
            - Path=/transactions/**
        - id: clients
          uri: lb://clients
          predicates:
            Path=/clients/**
        - id: credits
          uri: lb://credits
          predicates:
            Path=/credits/**
        - id: fees
          uri: lb://fees
          predicates:
            Path=/fees/**
        - id: reports
          uri: lb://reports
          predicates:
            Path=/reports/**

resilience4j:
  circuitbreaker:
    configs:
      default:
        sliding-window-size: 6
        failure-rate-threshold: 50
        wait-duration-in-open-state: 20s
        permitted-number-of-calls-in-half-open-state: 4
        slow-call-rate-threshold: 50
        slow-call-duration-threshold: 2s
    instances:
      account-service:
        base-config: default
      transaction-service:
        base-config: default
      clients:
        base-config: default
      credits:
        base-config: default
      fees:
        base-config: default
      reports:
        base-config: default
  timelimiter:
    configs:
      default:
        timeout-duration: 2s
    instances:
      account-service:
        base-config: default
      transaction-service:
        base-config: default
      clients:
       base-config: default
      credits:
       base-config: default
      fees:
       base-config: default
      reports:
       base-config: default
