apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway-server-app
  labels:
    app: gateway-server-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gateway-server-app
  template:
    metadata:
      labels:
        app: gateway-server-app
    spec:
      containers:
        - name: gateway-server-app
          image: ${REPOSITORY_NAME}.azurecr.io/${APP_NAME}:${IMAGE_TAG}
          imagePullPolicy: Always
          ports:
            - containerPort: 7001
          env:
            - name: PROFILE
              value: prod
            - name: EUREKA_DEFAULT_ZONE
              valueFrom:
                configMapKeyRef:
                  name: eureka-cm
                  key: eureka_default_zone